### ISSUE TITLE
傻逼

### ISSUE THREAD

**Issue by chenyuncai** [luoki/luoki.github.io#1]
这什么样的心态？，程序员中的败类吗？估计很多小伙伴看到那样的issue都觉得你好无聊，我忍不住替大家批斗你一下，傻缺

**Comment by Nothing-Works** [comment]
@chenyuncai 他就是 估计生活 各种不顺， 来 外面 丢脸，

**Comment by luoki** [comment]
@chenyuncai 看看你妈生出的傻B脸 ,只配凤姐
<img style="-webkit-user-select: none;background-position: 0px 0px, 10px 10px;background-size: 20px 20px;background-image:linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee 75%, #eee 100%),linear-gradient(45deg, #eee 25%, white 25%, white 75%, #eee 75%, #eee 100%);" src="https://avatars1.githubusercontent.com/u/8945203?s=400&amp;v=4">
@Nothing-Works 关你们屌事,傻B玩意
<img style="-webkit-user-select: none;background-position: 0px 0px, 10px 10px;background-size: 20px 20px;background-image:linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee 75%, #eee 100%),linear-gradient(45deg, #eee 25%, white 25%, white 75%, #eee 75%, #eee 100%);" src="https://avatars0.githubusercontent.com/u/18606648?s=400&amp;v=4">
